apiVersion: v1
kind: Service
metadata:
  name: insurance-charges-model-service
spec:
  selector:
    app: kf-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-charges-model-deployment
  labels:
    app: kf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kf-api
  template:
    metadata:
      labels:
        app: kf-api
    spec:
      containers:
        - name: kf-api
          image: 4oh4/kubernetes-fastapi:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: insurance-charges-model-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kf-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50