apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-charges-model-deployment
  labels:
    app: insurance-charges-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-charges-model
  template:
    metadata:
      labels:
        app: insurance-charges-model
    spec:
      containers:
        - name: insurance-charges-model
          image: eixsayy/finaltest:latest
          ports:
          - containerPort: 80
            protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
          env:  # Add this section
            - name: LOG_LEVEL
              value: "info"  # Set the desired log level (info, debug, etc.)
            - name: LOG_FORMAT
              value: "json"  # Set the desired log format (json, text, etc.)